### ISSUE TITLE
Broken in Browserify (shimmed) (this != window)

### ISSUE THREAD

**Issue by DylanLukes** [filamentgroup/fixed-sticky#25]
Simple as it says. `this` is passed into the fixedsticky.js IIFE. Browserify sets `this` to `undefined` in the context of each compiled module.

This can be worked around by wrapping the require in `(function (){...}).bind(window).call()`, but if you're using something like Traceur (where imports are statements, not expressions) it falls apart.

It should be `window`, not `this`.

**Comment by efuquen** [comment]
Hi. Can you cut a new version with this fix?  Really need this and would be nice to keep on official releases.  Thanks!

**Comment by zachleat** [comment]
Ah, sure! v0.1.4 should be available now.
