### ISSUE TITLE
Sticky fails when inside container

### ISSUE THREAD

**Issue by jeremiecarlson** [filamentgroup/fixed-sticky#36]
Reference: http://jsbin.com/yoronilovi/1/edit?html,css,js,output
Can't seem to figure out whats going on here. In the example "fixedsticky-on" never seems to get triggered as you scroll down the page.

If I move the nav outside the header, everything works as expected. (http://jsbin.com/yoronilovi/2/edit?html,css,js,output)

Am I missing something?

**Comment by zachleat** [comment]
Yeah, this took me awhile to learn back when I first started working on this polyfill.

Sticky elements are only sticky inside their parent. Instead of height: 2000px on .main use it on header.

**Comment by jeremiecarlson** [comment]
OK, Thanks. I didn't realize this was how sticky was supposed to work. Looks like it's going fit my needs then.
