### ISSUE TITLE
Publish to npm registry

### ISSUE THREAD

**Issue by mechanicalduck** [filamentgroup/fixed-sticky#38]
It would be helpful publishing this to npm registry, 
a package.json is already there anyway.

Thank you and
with best regards.

**Comment by tbranyen** [comment]
Needed this in a project, so I pushed the latest stable tag to NPM.  @zachleat I'll be happy to make you an owner and remove myself from publishing whenever is convenient for you.

**Comment by jefflembeck** [comment]
Hey @tbranyen,

Any chance you can make filamentgroup the owner?

**Comment by tbranyen** [comment]
@jefflembeck all set!

**Comment by Wilto** [comment]
guys

can’t you see that all this fighting is tearing me apart

**Comment by zachleat** [comment]
![](https://dl.dropboxusercontent.com/u/361291/gifs/fightme.gif)

**Comment by Wilto** [comment]
![](http://wil.to/_/attack.gif)

**Comment by zachleat** [comment]
![](https://dl.dropboxusercontent.com/u/361291/gifs/fight.gif)
