### ISSUE TITLE
A way to add styles to an element only when it's currently sticky?

### ISSUE THREAD

**Issue by benknight** [filamentgroup/fixed-sticky#39]
What I imagine to be a common use case is adding styles to an element when it's sticky, for example a box shadow to make it appear above the contents scrolling beneath it.

While this is easy when the polyfill is in effect, since it toggles the `fixedsticky-on` and `fixedsticky-off` classes, it's not possible when `position: sticky` has native support, as far as I know.

For browsers that support native sticky position, I think there is no property available on the DOM node object that tells you if the element is in a sticky or non-sticky state, so good old fashioned scroll event listeners would be necessary.  It would be great if this library could still toggle a class on the element to allow this kind of styling even when there is native sticky support.  Thoughts?

**Comment by benknight** [comment]
Update: It looks like forcing the polyfill in all browsers is probably the best way to achieve this, as described in the readme:

`FixedSticky.tests.sticky = false;`

I would love to find out if detecting the active / inactive state of sticky positioning will ever be possible in the native implementation, since special styling based on that seems like a pretty common use case.

**Comment by JonWallsten** [comment]
If you use jQuery:
What if you listen to the scroll event and check the sticky item's position(). Then compare it to the position's top/bottom value, if they match, it should be in sticky mode, and you can add the class, otherwise remove it. (It won't be exactly this simple but you get the point)

**Comment by zachleat** [comment]
When the polyfill behavior is used, the `fixedsticky-on` class means the sticky behavior is currently active on the element.

Let me know if you have additional questions!

**Comment by benknight** [comment]
Correct, that was noted in the issue description.  The suggestion is perhaps to add a mechanism for styling when an element is sticky and sticky position has native support (i.e. when the Polyfill is not in effect).

**Comment by zachleat** [comment]
Oh! Sorry—I misunderstood. Do you have an example of the style you’re trying to add?

Seems like the workaround here (use the polyfill everywhere) might be acceptable for now, since so few native implementations exist (and in fact, native support is diminishing).

**Comment by benknight** [comment]
I agree about the workaround.  Thanks for discussing!
