### ISSUE TITLE
Support for overflow

### ISSUE THREAD

**Issue by mechanicalduck** [filamentgroup/fixed-sticky#40]
Support for overflowing would be very useful, 
especially when height: 100% has to be used on the parent (html, body) elements.

Thanks.
With best regards

**Comment by zachleat** [comment]
We consider overflow to be somewhat of an anti-pattern, given spotty mobile support. Therefore, we probably won’t add this—sorry!

The readme does currently say: “This plugin does not support overflow on parent elements.”
