### ISSUE TITLE
Simply can't get it working

### ISSUE THREAD

**Issue by Marmeladekuchen** [filamentgroup/fixed-sticky#57]
http://jsfiddle.net/1geengno/1/

I suppose I did everything the way it is described in the readme, still can't get it running.
Can anybody help?

**Comment by paulstraw** [comment]
@Marmeladekuchen, move your call to `$( '.fixedsticky' ).fixedsticky();` _below_ the fixed-sticky code. You're trying to call it before it exists. :smiley:

**Comment by Marmeladekuchen** [comment]
Thanks Paul!

I guess this proves my Javascript skills big time. ;)

**Comment by paulstraw** [comment]
:ok_hand: No problem!
